version: '3'


services:

  nu_lessons:
    container_name: nu_lessons
    image: nu_lessons
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    command: /app/compose/gunicorn.sh
    volumes:
      - ./assets:/app/staticfiles
      - ./media:/app/media

  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - nu_lessons
    ports:
      - 80:8000
    volumes:
      - ./assets:/app/assets
      - ./media:/app/media
      - ./compose/nginx/conf.d:/etc/nginx/conf.d
